### ISSUE TITLE
Low sync speed (bps)

### ISSUE THREAD

**Issue by Luca-Poggi** [availproject/avail#298]
## Description
Hello, I'm Luca from :ice_cube: Iceberg Nodes :ice_cube: 
This is not properly a bug, but I would like to signaling this probable issue.
We have migrated our node from Kate Testnet to Goldberg Testnet. In syncing Kate Testnet we are experiencing a very slow sync speed: about 6.6 bps - blocks per second usually per our experience it is something like 300-600 range depending on circumstances. The hardware is far above the minimum specs recommended, also we are NOT using any particular sync flag like --sync fast or --sync warp or other. But also for a full sync it should be more quickly than 6.6 bps usually.

## Steps to Reproduce
Lanch a Goldberg Testnet full node and sync from scratch.

## Expected Behavior
Usually 300-600 bps range or higher.

## Actual Behavior
About 6.6 bps.

## Additional Information
It seems that also other nodes are in the same situation:
Ordered by best block:
![image](https://github.com/availproject/avail/assets/59626126/e9031062-86fd-4d97-a0d4-4617b7415ed1)

Ordered by uptime:
![image](https://github.com/availproject/avail/assets/59626126/f3185ee0-20e2-47ea-83fd-bc0b49e2917d)

**Comment by jakubcech** [comment]
Hey @Poggi-Luca, thanks for the thorough report. We're currently looking into this. Will keep this updated.

**Comment by markopoloparadox** [comment]
@Poggi-Luca 
We were able to replicate the issue and found what was causing it. The fix will be merged quite soon together with a new node release.

**Comment by Poggi-Luca** [comment]
Awesome! Great work guys! The fix was very quickly!
Feel free to close this issue as per your best convenience.

**Comment by markopoloparadox** [comment]
This was fixed in version v1.8.0.2: https://github.com/availproject/avail/releases/tag/v1.8.0.2
