### ISSUE TITLE
bug:  docker container keeps crashing

### ISSUE THREAD

**Issue by 0xMadao** [availproject/avail#324]
# Bug Report

## Description
the docker container keeps restarting again and agin, when I use the `dmesg`, find the  error  message as following: `[Tue Dec  5 22:26:31 2023] traps: data-avail[420675] trap invalid opcode ip:557516a4d6ae sp:7fff07a40348 error:0 in data-avail[557514bc1000+26d6000]` 

## Steps to Reproduce

1. follow the guide [How to Run a Full Node with Docker](https://docs.availproject.org/operate/node/docker/)

## Expected Behavior

container runs normally

## Actual Behavior
container keeps crashing

## Additional Information
- **os:** Ubuntu 20.04 LTS
- **kernel:** 5.4.0-29-generic
- **cpu:** Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
- **cpu cores**: 8
- **memory:** 2G
- **arch:** x86-64
- **running commad:** `sudo docker run -v $(pwd)/state:/da/state:rw -p 30333:30333 -p 9615:9615 -p 9944:9944 -d --restart unless-stopped availj/avail:v1.8.0.3 --chain goldberg --name "MyAweasomeInContainerAvailAnode" -d /da/state`
- **node type:** full node

**Comment by markopoloparadox** [comment]
@0xMadao Can you try the docker image and/or the binary on a newer CPU?

**Comment by 0xMadao** [comment]
> @0xMadao Can you try the docker image and/or the binary on a newer CPU?

which cpu version suggest? I have tried `Intel(R) Xeon(R) Gold 6246R CPU @ 3.40GHz` but tells me `GLIBC_2.29` and `GLIBC_2.28` not found

**Comment by markopoloparadox** [comment]
If you are running Ubuntu 20 try the Ubuntu 20 binary on that Gold 6246R CPU. Link: https://github.com/availproject/avail/releases/download/v1.8.0.4/x86_64-ubuntu-2004-data-avail.tar.gz

**Comment by 0xMadao** [comment]
> If you are running Ubuntu 20 try the Ubuntu 20 binary on that Gold 6246R CPU. Link: https://github.com/availproject/avail/releases/download/v1.8.0.4/x86_64-ubuntu-2004-data-avail.tar.gz

using ` Intel(R) Xeon(R) Silver 4108 ` works now, suggest add the requirement of CPU to the doc

**Comment by markopoloparadox** [comment]
> > If you are running Ubuntu 20 try the Ubuntu 20 binary on that Gold 6246R CPU. Link: https://github.com/availproject/avail/releases/download/v1.8.0.4/x86_64-ubuntu-2004-data-avail.tar.gz
> 
> using `Intel(R) Xeon(R) Silver 4108` works now, suggest add the requirement of CPU to the doc

Makes sense. I will copy and paste what the Polkadot guys have. Which is: "Intel Ice Lake, or newer (Xeon or Core series); AMD Zen3, or newer (EPYC or Ryzen);"
