### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by BullForAReason** [availproject/avail#354]
![Screenshot (45)](https://github.com/availproject/avail/assets/104497203/4c3be0b5-cc7e-4cdf-a59c-056e03c61abd)
can anyone confirm me if my node is running properly or not

**Comment by thewoo02** [comment]
> ![Screenshot (45)](https://private-user-images.githubusercontent.com/104497203/293206474-4c3be0b5-cc7e-4cdf-a59c-056e03c61abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjc0NjcsIm5iZiI6MTcwNDIyNzE2NywicGF0aCI6Ii8xMDQ0OTcyMDMvMjkzMjA2NDc0LTRjM2JlMGI1LWNjN2UtNGNkZi1hNTljLTA1NmUwM2M2MWFiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQyMDI2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmNjN2YwMDRlY2RlNmEzY2RhYjRkY2I3MTk2NDZmNmVlYThmMzVjNmJjOThkODkwYjA5OGFkMTdiMWJkNzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._MkCaDXclpBrXSuLi-2W0Joe-paUvI0f0DAalz7xHO0) can anyone confirm me if my node is running properly or not

please can i guide on how to got yur node running?

**Comment by Leouarz** [comment]
Hello @BullForAReason 
It seems you are running a node on the old Kate testnet and not on Goldberg.
Please refer to the guides here : https://docs.availproject.org/
And pls for any kind of support go to discord as this place is for issues and not custom support.

**Comment by BullForAReason** [comment]
I'm unable to join avail discord that's why i'm here

**Comment by Leouarz** [comment]
Either it's temporary or you were banned, unfortunaly here is not the place to discuss discord issues.

**Comment by BullForAReason** [comment]
ok
