### ISSUE TITLE
bug: block synchronization is stocked if the node is started from a servere, where a node started and stopped previously

### ISSUE THREAD

**Issue by zhengqian8958** [availproject/avail#382]
# Bug Report

block synchronization is stocked if the node is started from a servere, where a node started and stopped previously. The stocked point is the block hight of the previous running round

## Description

the synchronization stocked with following error message:

> Jan 23 20:24:41 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:24:41 🔍 Discovered new external address for our node: /ip4/206.217.136.229/tcp/30333/p2p/12D3KooWPekRv4ADsX7aqTDKHjNBB4En8Ndhvp4HqeQaaZ76rR7e
> Jan 23 20:24:45 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:24:45 ⚙️  Syncing, target=#328646 (8 peers), best: #276333 (0x12c9…298d), finalized #271872 (0x9e17…e455), ⬇ 9.0MiB/s ⬆ 629.9kiB/s
> Jan 23 20:24:50 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:24:50 ⚙️  Syncing  0.0 bps, target=#328646 (8 peers), best: #276333 (0x12c9…298d), finalized #271872 (0x9e17…e455), ⬇ 10.9MiB/s ⬆ 1.4MiB/s
> Jan 23 20:24:55 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:24:55 ⚙️  Syncing  0.0 bps, target=#328646 (8 peers), best: #276333 (0x12c9…298d), finalized #271872 (0x9e17…e455), ⬇ 12.4MiB/s ⬆ 746.6kiB/s
> Jan 23 20:25:00 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:25:00 ⚙️  Syncing  0.0 bps, target=#328646 (8 peers), best: #276333 (0x12c9…298d), finalized #271872 (0x9e17…e455), ⬇ 12.7MiB/s ⬆ 139.1kiB/s
> Jan 23 20:25:00 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:25:00 ❌ Error while dialing /dns/telemetry.avail.tools/tcp/8001/x-parity-ws/%2Fsubmit: Custom { kind: Other, error: Timeout }
> Jan 23 20:25:05 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:25:05 ⚙️  Syncing  0.0 bps, target=#328646 (8 peers), best: #276333 (0x12c9…298d), finalized #271872 (0x9e17…e455), ⬇ 13.1MiB/s ⬆ 75.6kiB/s
> Jan 23 20:25:10 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:25:10 ⚙️  Syncing  0.1 bps, target=#328646 (8 peers), best: #276334 (0xa880…f64a), finalized #271872 (0x9e17…e455), ⬇ 11.8MiB/s ⬆ 79.8kiB/s
> Jan 23 20:26:16 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:26:16 ⚙️  Syncing  0.0 bps, target=#328646 (8 peers), best: #276335 (0x557b…725a), finalized #271872 (0x9e17…e455), ⬇ 541.7kiB/s ⬆ 4.8kiB/s
> Jan 23 20:26:24 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:26:24 ❌ Error while dialing /dns/telemetry.avail.tools/tcp/8001/x-parity-ws/%2Fsubmit: Custom { kind: Other, error: Timeout }
> Jan 23 20:26:24 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:26:24 ⚙️  Syncing  0.0 bps, target=#328647 (2 peers), best: #276335 (0x557b…725a), finalized #271872 (0x9e17…e455), ⬇ 297.2kiB/s ⬆ 48.1kiB/s
> Jan 23 20:26:29 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:26:29 ⚙️  Syncing  0.1 bps, target=#328651 (5 peers), best: #276336 (0x6b53…b791), finalized #271872 (0x9e17…e455), ⬇ 1.2MiB/s ⬆ 156.9kiB/s
> Jan 23 20:26:29 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:26:29 👴 Applying authority set change scheduled at block #273900
> Jan 23 20:26:30 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:26:30 👴 Applying GRANDPA set change to new set with 290 authorities
> Jan 23 20:26:34 racknerd-2233d3 data-avail[165179]: 2024-01-23 20:26:34 ⚙️  Syncing  0.0 bps, target=#328651 (8 peers), best: #276336 (0x6b53…b791), finalized #271872 (0x9e17…e455), ⬇ 1.2MiB/s ⬆ 75.5kiB/s
> Jan 23 20:26:48 racknerd-2233d3 systemd[1]: availd.service: Main process exited, code=killed, status=9/KILL
> Jan 23 20:26:48 racknerd-2233d3 systemd[1]: availd.service: Failed with result 'signal'.
> Jan 23 20:26:48 racknerd-2233d3 systemd[1]: availd.service: Consumed 2min 47.396s CPU time.
> Jan 23 20:28:49 racknerd-2233d3 systemd[1]: availd.service: Scheduled restart job, restart counter is at 375.
> Jan 23 20:28:49 racknerd-2233d3 systemd[1]: Stopped Avail Validator.

## Steps to Reproduce

1. Start the node and finish the synchronization
2. Stop the node, where the block hight is X
3. Remove the existing repo and resynchronize/recompile the sw
4. Start the node from very beginning (without any exisiting block data)

## Expected Behavior

Node can synchronize to the newest block hight

## Actual Behavior

Node synchonization is stocked at block hight X

## Additional Information

According to the following console output:

> Discovered new external address for our node: /ip4/206.217.136.229/tcp/30333/p2p/12D3KooWPekRv4ADsX7aqTDKHjNBB4En8Ndhvp4HqeQaaZ76rR7e

where the IP is exactly the server IP. It seems like the SW considers the removed node, which was running in this IP as a best peer to synchronize block data. But the previous node is already stopped and doesn't exist anymore, which means no new block data is available since it was stopped. Therefore the current node is just waiting for this non-existed node to synchronize the block data and stocked.

**Comment by Leouarz** [comment]
Hello, this issue will be fixed in the next release along with instruction to start the node.
