### ISSUE TITLE
Error importing block xxx: block has an unknown parent 

### ISSUE THREAD

**Issue by buddh0** [availproject/avail#396]
# Bug Report

## Description

<img width="1205" alt="image" src="https://github.com/availproject/avail/assets/7995985/e973111d-8e33-4fbf-8212-4e36942fc56f">

## Steps to Reproduce

I start a full node on aliyun, system
<img width="960" alt="image" src="https://github.com/availproject/avail/assets/7995985/1e973bc9-a0e1-408a-bf00-c49b51550764">
1. run using binary v1.09
2. start command
```
./data-avail -d ./data --chain goldberg --name RollTheWordLabs
```
3. pkill data-avail and restart , then issue occured in the above picture
I'm sure that I have't force kill

**Comment by Leouarz** [comment]
Hello, this is a known issue on the Goldberg network, it will be fixed in the next binary release.
