### ISSUE TITLE
bug:  Cannot create a runtime error=Other("runtime requires function imports which are not present on the host: 'env:ext_hosted_header_builder_build_version_2'")

### ISSUE THREAD

**Issue by kamrannB** [availproject/avail#402]
# Bug Report

I have successfully created and started my node but in my logs i see these errors and can not fix. WHat is the reason for this error

2024-02-05 23:20:29 Cannot create a runtime error=Other("runtime requires function imports which are not present on the host: 'env:ext_hosted_header_builder_build_version_2'")
Feb 05 23:20:29 ip-172-31-41-155 data-avail[416720]: Error: Service(Client(RuntimeApiError(Application(VersionInvalid("Other error happened while constructing the runtime: runtime requires function imports which are not present on the host: 'env:ext_hosted_header_builder_build_version_2'")))))
Feb 05 23:20:29 ip-172-31-41-155 systemd[1]: availd.service: Main process exited, code=exited, status=1/FAILURE

**Comment by Leouarz** [comment]
Hello, what version of the binary are you using ? Can you also paste the command you are using ?
