### ISSUE TITLE
bug: Discord Server Dcounter Bot

### ISSUE THREAD

**Issue by MrExcel2019** [availproject/avail#417]
# Bug Report

## Description
Dcounter server bot verification link showing internal server error

## Expected Behavior
Server error
## Actual Behavior
The below images show the current behavior of the verification link
![screenshot-github com-2024 02 15-02_24_22](https://github.com/availproject/avail/assets/56793406/8b3c724e-a7b2-416a-ac84-b0413ae25e21)

**Note1**-----> 
_The above image shows a redirect link to Avail Discord channel_

![image](https://github.com/availproject/avail/assets/56793406/f8d09636-521e-4175-b090-f9c15359696f)
**Note 2**---->
The above image shows the output after clicking on the link supply by **dcounter bot**

## Additional Information
A swift response to this will allow others to join the server and become a part of the community.

**Comment by Grraarrgghh** [comment]
The discord link there in face is referring to the DoubleCounter Discord channel to report the bug (Avail does not maintain the bot, only uses it as a service). They do not currently have any reported outages so this is either a brief blip in their service availability or an issue with your network.
