### ISSUE TITLE
bug: This that needed to be fixed in Avail

### ISSUE THREAD

**Issue by Speedevs** [availproject/avail#428]
# Bug Report

Check the [contributing guide](https://github.com/availproject/avail/blob/main/.github/CONTRIBUTING.md)

## Description
<1. FAUCET been down for hours>
<2. Get some errors after compiling>
<3. Hard to access explorer>
4. Not mobile friendly the explorer (Need a nicer User interface) no Normal web 2 "Dev" user going to understand that apart from web 3 devs

**Comment by Leouarz** [comment]
Hey, thank you for your comment but those suggestions are not meant for the node repo. More tooling are going to be there eventually.

**Comment by Speedevs** [comment]
Ah okay thanks

**Comment by Speedevs** [comment]
Please can I know where it will go to if possible

**Comment by Leouarz** [comment]
You can go to discord or telegram to get more information in you enquiries
