### ISSUE TITLE
bug: i have 10 avail and it keeps bringing an error message when i try to join the pools.

### ISSUE THREAD

**Issue by oluwatoosyn** [availproject/avail#429]
# Bug Report

Check the [contributing guide](https://github.com/availproject/avail/blob/main/.github/CONTRIBUTING.md)

## Steps to Reproduce

1.
2.
3.

**Comment by Leouarz** [comment]
Hello, this is due to the existential deposit, if your account is lower than a certain amount, 0.1 AVL, it will be considered empty and destroyed.
