### ISSUE TITLE
Discord server faucet bug: 

### ISSUE THREAD

**Issue by Traicye** [availproject/avail#433]
# Bug Report

Check the [contributing guide](https://github.com/availproject/avail/blob/main/.github/CONTRIBUTING.md)

## Description
After using the discord faucet for the first time, it links that particular wallet address to your discord account. When interacting with the avail clash of nodes, for example, the partnership with Dymension that recently closed, you'll need to change your wallet address from the previous address you used for the onchain identity task. Even after using the change address channel, I still get an error saying user ID does not match. I tried it for different wallets and i still got the same feedback. 

## Steps to Reproduce

1. Create wallet on goldberg
2. Type in "/deposit:[wallet adress]" on discord channel: Goldberg Faucet 
3. Deploy rollapp on dymension selecting avail as your data availability layer
4. Copy the avail wallet address given to you on your linux environment 
5. Go to the change address channel on the discord, follow the format given to you by the discord bot and then change wallet address. 
6. Go to the goldberg facuet channel and attempot to request faucet

## Expected Behavior
I expect that there would be a feedback that tells me that wallet address A has been changed to wallet address B. 
I expect that when i go to the goldberg faucet channel and input my new wallet address for dymension, I would get a success feedback.

## Actual Behavior
User ID does not match

## Additional Information
I ran into this problem a lot of time while I was participating in the clash of nodes program. I even tried just linking my subwallet avail address to the faucet, but i still got errors sending from my subwallet. It made the whole processing frustrating cos I kept trying to get faucet and start the whole process again once the linux environment generated a new wallet and seedphrase for me for as many times as I tried doing the tasks.

**Comment by Leouarz** [comment]
Hello, thanks for raising this issue, but this is avail node repo, pls report this in discord or telegram
