### ISSUE TITLE
feat: Feedback for faucet wallet address change on the discord.

### ISSUE THREAD

**Issue by Traicye** [availproject/avail#434]
# Feature Request

Check the [contributing guide](https://github.com/availproject/avail/blob/main/.github/CONTRIBUTING.md)

## Summary
It would be beneficial and make it easier to participate in Avail's testnet environment if the discord bot on the change wallet address channel gives a feedback saying if the address was successfully changed or not, or providing feedback on the old adress and new address.

## Detailed Description
Providing feedback on the wallet address change would make it easier to track wallets used seeing that different tasks in the avail ecosystem would require for different wallet addresses. 
For example, the wallet address for the Dymension partner challenge differs greatly from the wallet address for the goldberg onchain identity task. 
Creating a feedback mechanism would improve user experience greatly and would make it easier to interact with the avail faucet and in extension, the avail ecosystem. 

## Use Cases
Faucet use for testing avail or partcipating in the clash of nodes challenge. 

## Alternative Solutions
I've tried scrolling through my inputs to the discord channel to find which address was changed from and which address was changed to. I've tried trying to keep track of the changes (especially when i run into errors on the partner challenges like deploying a rollapp or an appchain), but i keep running into issues when it comes to using the faucet. I just keep getting user ID does not match and I have no idea why. IT really did frustrate my experience when testing and particpating in the clash of nodes challenge. I ended up not being able to find a solution and missed out on the challenge. 

An alternative solution can be a checkmark or a cancel that clearly states whether the wallet address change was succesful or not.

**Comment by Leouarz** [comment]
Hello, thanks for raising this issue, but this is avail node repo, pls report this in discord or telegram
