### ISSUE TITLE
feat: Decentralized Key Generation (DKG) as a Service on Avail

### ISSUE THREAD

**Issue by akuon** [availproject/avail#439]
**Summary:** Integrate a Decentralized Key Generation (DKG) service into the Avail network, allowing users to securely generate and manage cryptographic keys in a distributed and trustless manner.

**Detailed Description:**

Avail's secure enclave technology provides a foundation for building trustless applications. However, securely generating and managing cryptographic keys remains a significant challenge. This feature request proposes incorporating a DKG service within Avail, enabling users to:

* **Generate shared keys:** Multiple parties can collaboratively generate cryptographic keys without any single entity possessing complete control.
* **Threshold signatures:** Implement threshold signature schemes where a certain number of parties need to contribute to sign a transaction, enhancing security and fault tolerance.
* **Key management:** Securely store and manage keys generated through DKG within Avail enclaves, ensuring confidentiality and integrity.

**Use Cases:**

* **Multi-party computation (MPC):** Securely conduct computations on private data without revealing the underlying information, requiring distributed key generation for participant authentication and data integrity.
* **DAO governance:** Implement secure and transparent voting mechanisms within DAOs, leveraging DKG for key generation and threshold signatures to authorize actions without centralized control.
* **Custody wallets:** Enhance the security of custody wallets by employing DKG to generate and manage keys across multiple servers or enclaves, mitigating single points of failure and insider threats.

**Alternative Solutions:**

* **Hardware Security Modules (HSMs):** While offering strong security, HSMs introduce centralized points of control and potential vulnerabilities.
* **Shamir's Secret Sharing:** This manual key splitting technique lacks the automation and trustless environment offered by DKG.

**Additional Context:**

* **Integration with existing Avail services:** Seamlessly integrate the DKG service with other Avail offerings like secure computation and confidential storage for a comprehensive suite of privacy-preserving functionalities.
* **Standardization and interoperability:** Adhere to established DKG standards (e.g., BLS) to ensure compatibility with other blockchain ecosystems and applications.
* **Security considerations:** Conduct thorough security audits and implement best practices for key management within Avail enclaves to guarantee the integrity and confidentiality of generated keys.

**Benefits:**

* **Enhanced security:** Mitigates the risks associated with centralized key generation and storage, fostering trust and transparency in decentralized applications.
* **Improved user experience:** Simplifies key management for users by providing a secure and user-friendly interface within the Avail ecosystem.
* **Unlocks new use cases:** Enables the development of novel applications requiring secure and distributed key management, expanding the potential of Avail technology.

**Challenges:**

* **Technical complexity:** Implementing a robust and efficient DKG service while maintaining security and scalability requires careful design and engineering.
* **User adoption:** Educating users on the benefits and proper usage of DKG is crucial for widespread adoption within the Avail ecosystem.
* **Regulatory considerations:** Depending on the specific implementation, regulatory compliance regarding key management and cryptographic protocols might need to be addressed.

By incorporating a DKG service, Avail can empower users with secure and trustless key management capabilities, fostering the development of innovative and privacy-preserving decentralized applications while addressing the inherent challenges associated with centralized key generation and storage. This feature aligns with Avail's vision of building a secure and scalable foundation for future decentralized applications.

**Comment by Leouarz** [comment]
Hello, I think you may have mistaken us with Ternoa due to our partnership with them. This is not the correct place to open a discussion, you can rather go to the organization's discussions.
