### ISSUE TITLE
bug: Avail Goldberg Testnet website page https://goldberg.avail.tools lacks a lot

### ISSUE THREAD

**Issue by wnhedaxx** [availproject/avail#442]
it takes alot of time to use Avail Goldberg Testnet please insure to make it fast and reliable
.....
also i am unable to see my staked amount of avail tokens in pool page
![Uploading Screenshot (116).png…]()

**Comment by Leouarz** [comment]
RPC seems to be usable and screenshot is not displayed properly.

**Comment by wnhedaxx** [comment]
You closed it

**Comment by wnhedaxx** [comment]
You closed it @Leouarz 
Are you guys handling my your community like this way.

I am experiencing this prob and you made lame excuse screenshot not displayed properly ..i can provide you a proper screnshot man

**Comment by Leouarz** [comment]
There are multiple RPCs, most of the time usable, they are handling a lot of load. It's normal to experience this and we are working on improving it, nothing more there to say.
