### ISSUE TITLE
bug: i set on-chain identity 3 times but it still shows empty

### ISSUE THREAD

**Issue by wnhedaxx** [availproject/avail#444]
# Bug Report

i set on-chain identity 3 times but it still shows empty please look into this matter 

## Description
we are not able to see the on-chain identity once we set it 

## Steps to Reproduce

1. visit https://goldberg.avail.tools/#/accounts
2. choose your account and click on 3 dots, you will see set on-chain identity option click on it
3. set your details and save it and brodcast the transction
4. repeat steps and you will see your on-chain identity is not saved

## Expected Behavior
i expect it will save the on-chain identity which i will set

![Screenshot (118)](https://github.com/availproject/avail/assets/70830772/713e44d4-2d61-49af-897b-20d0210ab1e3)
![Screenshot (119)](https://github.com/availproject/avail/assets/70830772/6792bb04-43cb-4953-a377-ae98d67868aa)

**Comment by wnhedaxx** [comment]
https://goldberg.avail.tools/#/extrinsics/decode/0xad02840088ff5da4cc516dfb46eae6d6371a4f5bcae7d845bc411234ae27d0e8bd43e91301087477473a2a5a8c18bdb370369872dc2f28bf5f1a4b6d40067b0805b79e06312c158c82822c9ed8ca241f950bdd91f01d78c3e6ea1dec0e6eca83e02bb27880d40020000025010408446973636f72640b69636f6e6963626f737306617661696c0000001873686179616e6268617430303940676d61696c2e636f6d00000a40696e5061696e3039


here is the transaction of on-chain identity still it does not shows on-chain identity while checking

**Comment by Leouarz** [comment]
Hello, you can go to Discord to get specific advices, without a real transaction it's not possible to know what's wrong.

**Comment by wnhedaxx** [comment]
@Leouarz 
I am taking about the bug i experienced sir.
I set on chain identity 3 times...but it doesn't shows on chain identity data which i have saved i have mentioned steps to reproduce this problem...
You can reproduce it and check it's validation 😶

**Comment by Leouarz** [comment]
The issue is not reproducible on our end. Also lot of ppl managed to get their onchain identity (you can get help on discord) and I have mentionned to check your funds. 
You have not given your address or any block to check.
Also it's not a place to get support (since it's not a bug, it's support)

**Comment by wnhedaxx** [comment]
5FALEEVrULLPPazuaRTiruh5TBtMW8YwWZuaQ4drY2t2Q42Z
Here is my address
