### ISSUE TITLE
transfer_keep_alive return wasm error

### ISSUE THREAD

**Issue by gtmickey** [availproject/avail#482]
extrinsic: 41028400ba264b7c2da1e38e85f2fbff19a75cd21536bdadabf57839f8c9bd2e074dff3f01aa743be4591b872fad9a7181f09d35294fe9eb9d0fe19c8b56fee2b40e9f5056fc4135648567fe3a71a57b3f7bf0543fe3688204b6da22222206a75a6fa76b89150304000603008bebfe7c3f82aa1e5130017d58aa03bd6806a8c7cace9fcf0516dc2a7fdbeb64070070c9b28b

Exception: {code: 1002, message: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x36e7c0 - <unknown>!rust_begin_unwind
    1: 0xef50 - <unknown>!core::panicking::panic_fmt::h6dad0405f48e39e2
    2: 0x2c96a0 - <unknown>!TaggedTransactionQueue_validate_transaction, data: RuntimeApi("Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x36e7c0 - <unknown>!rust_begin_unwind\n    1: 0xef50 - <unknown>!core::panicking::panic_fmt::h6dad0405f48e39e2\n    2: 0x2c96a0 - <unknown>!TaggedTransactionQueue_validate_transaction")}

**Comment by ToufeeqP** [comment]
Hey @gtmickey, it seems you've sent a transaction using an incompatible interface, such as an outdated explorer. I recommend using the latest explorer available at [this link](https://github.com/availproject/avail-apps/releases/tag/v1.8-rc8) and attempting to submit the transaction again. If this doesn't resolve the problem, please provide additional details about the chain you're using and the interface used for transaction submission. This will help us assist you more effectively.
