### ISSUE TITLE
Does avail-apps v1.8-rc8 changed will sync to avail chain spec/metadata?

### ISSUE THREAD

**Issue by gtmickey** [availproject/avail#489]
As [https://github.com/availproject/avail-apps/releases/tag/v1.8-rc8](https://github.com/availproject/avail-apps/releases/tag/v1.8-rc8) include types changed, will this types update sync to chain spec or metadata?

**Comment by Leouarz** [comment]
Hey, 
You can ask question on other medium such as discord. This is not an issue.
Please don't add the bug label if there is not bug.
Please in case of an issue open it in the corresponding repository (here, the repo is avail, not avail-apps)

Types changes a lot for us if you track what's happening. It's mostly related to metadata as chainspec do not change.
