### ISSUE TITLE
feat: Documentation update

### ISSUE THREAD

**Issue by tfius** [availproject/avail#535]
# Feature Request

Please update information on what ports are required.

## Summary
Challenge started with different ports, started with 30333, then 37000. Http port 7000 and wss on 433. 

## Detailed Description
It would be nice that required ports are specified in documentation.

## Use Cases
Notifiy user when runing light client behind firewall what ports to forward.

## Alternative Solutions
None. Update documentation.

## Additional Context
Please keep documentation up to date.

**Comment by Leouarz** [comment]
This is the avail node repo and not the light client.
