### ISSUE TITLE
bug: Transaction Validation Failure: RuntimeCall::TechnicalCommittee Decoding Error

### ISSUE THREAD

**Issue by johnt9x** [availproject/avail#590]
# Bug Report

## Description
When attempting to perform a transaction using balances.transferKeepAlive, the node encounters a runtime panic with the error: "Bad input data provided to validate_transaction: Could not decode RuntimeCall::TechnicalCommittee.0".

## Steps to Reproduce
1. Start the Avail node with the following command
ExecStart=/root/avail/avail-node --base-path /root/avail/node-data --chain turing --rpc-external  --rpc-port 9944 --rpc-cors=all --name VNBnode  --rpc-methods Unsafe --pruning archive --rpc-max-connections 300 --unsafe-da-sync --out-peers 100 --in-peers 100
2. Use Polkadot.js or other compatible tools to send a balances.transferKeepAlive transaction.
https://polkadot.js.org/apps/?rpc=wss://rpc-avail.vnbnode.com#/accounts
3. Observe the node logs for the runtime panic error.

## Expected Behavior
The transaction should be processed successfully without causing a runtime panic.

## Actual Behavior
The node panics with the following error message:
Thread 'tokio-runtime-worker' panicked at 'Bad input data provided to query_info: Could not decode `RuntimeCall::TechnicalCommittee.0`:
Could not decode `Call`, variant doesn't exist
', runtime/src/apis.rs:78
This is a bug. Please report it at:
        https://github.com/availproject/avail/issues/new/choose
2024-05-16 15:45:19 Evicting failed runtime instance error=Runtime panicked: Bad input data provided to query_info: Could not decode `RuntimeCall::TechnicalCommittee.0`:
Could not decode `Call`, variant doesn't exist

## Additional Information
**Additional Information**
Node Version: v2.2.2.0-rc1
Operating System: Ubuntu 22.04
Runtime Information:
specName: avail
implName: avail
authoringVersion: 12
specVersion: 31
implVersion: 0
transactionVersion: 1
stateVersion: 1
**Command Used:** /root/avail/node-data --chain turing --rpc-external  --rpc-port 9944 --rpc-cors=all --name VNBnode  --rpc-methods Unsafe --pruning archive --rpc-max-connections 300 --unsafe-da-sync --out-peers 100 --in-peers 100

**Additional Context**
I used https://temp-explorer.avail.so/?rpc=wss://rpc-avail.vnbnode.com#/accounts and it worked. However, using [Polkadot.js.org](https://polkadot.js.org/) resulted in the error.

**Log excerpt:**
May 16 15:45:19 ubuntu-4gb-hil-1 avail-node[351814]: Thread 'tokio-runtime-worker' panicked at 'Bad input data provided to query_info: Could not decode `RuntimeCall::TechnicalCommittee.0`:
May 16 15:45:19 ubuntu-4gb-hil-1 avail-node[351814]: Could not decode `Call`, variant doesn't exist
May 16 15:45:19 ubuntu-4gb-hil-1 avail-node[351814]: ', runtime/src/apis.rs:78
May 16 15:45:19 ubuntu-4gb-hil-1 avail-node[351814]: This is a bug. Please report it at:
May 16 15:45:19 ubuntu-4gb-hil-1 avail-node[351814]:         https://github.com/availproject/avail/issues/new/choose
May 16 15:45:19 ubuntu-4gb-hil-1 avail-node[351814]: 2024-05-16 15:45:19 Evicting failed runtime instance error=Runtime panicked: Bad input data provided to query_info: Could not decode `RuntimeCall::TechnicalCommittee.0`:
May 16 15:45:19 ubuntu-4gb-hil-1 avail-node[351814]: Could not decode `Call`, variant doesn't exist

**Comment by Adamtruong6868** [comment]
nice!

**Comment by Leouarz** [comment]
Hey the problem here comes from the types, polkadot UI does not have the necessary data to construct a transaction. You should use explorer.avail.so
