### ISSUE TITLE
avail substrate api sidecar 

### ISSUE THREAD

**Issue by malingzhao** [availproject/avail#617]
{"code":500,"message":"createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [144, 29]/[144,29]","stack":"Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [144, 29]/[144,29]\n    at createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types-create/cjs/create/type.js:54:22)\n    at TypeRegistry.createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types/cjs/create/registry.js:230:52)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:331:25)\n    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:169:20)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:190:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","level":"error"}root@testWallet:/data/avail#

**Comment by kroos47** [comment]
Could you explain a bit more on this error?

**Comment by malingzhao** [comment]
use the substrate api sidecar

**Comment by malingzhao** [comment]
https://github.com/availproject/avail-substrate-api-sidecar
use this docker build also has the error

**Comment by kroos47** [comment]
if using docker use `docker pull availj/sidecar-api:zenitsu`

**Comment by malingzhao** [comment]
ok

**Comment by malingzhao** [comment]
now is ok, thank you very much

**Comment by kroos47** [comment]
closing this as it resolved

**Comment by yaoyf888** [comment]
@malingzhao Is your substrate-api-sidecar mainnet working? Why I request 127.0.0.1:8080 / blocks/head error 

{
    "code": 500,
    "message": "createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.killPrefix:: Struct: failed on args: {\"prefix\":\"Bytes\",\"subkeys\":\"u32\"}:: decodeU8aStruct: failed at 0x030072a4822f2712d20fb87f345238e8… on prefix (index 1/2): Bytes:: Bytes length 2191815168 exceeds 10485760",
    "stack": "Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.killPrefix:: Struct: failed on args: {\"prefix\":\"Bytes\",\"subkeys\":\"u32\"}:: decodeU8aStruct: failed at 0x030072a4822f2712d20fb87f345238e8… on prefix (index 1/2): Bytes:: Bytes length 2191815168 exceeds 10485760\n    at createTypeUnsafe (/Users/yaoyf/WorkSpace/Bitmart/code/substrate-api-sidecar/node_modules/@polkadot/types-create/cjs/create/type.js:54:22)\n    at TypeRegistry.createTypeUnsafe (/Users/yaoyf/WorkSpace/Bitmart/code/substrate-api-sidecar/node_modules/@polkadot/types/cjs/create/registry.js:230:52)\n    at RpcCore._formatOutput (/Users/yaoyf/WorkSpace/Bitmart/code/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:331:25)\n    at RpcCore._formatResult (/Users/yaoyf/WorkSpace/Bitmart/code/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:169:20)\n    at callWithRegistry (/Users/yaoyf/WorkSpace/Bitmart/code/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:190:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "level": "error"
}

**Comment by malingzhao** [comment]
turing testnet is ok, how did you install the main node , could you share your install guides of mainnet, I will test for it

**Comment by yaoyf888** [comment]
I use deployment docker way you mentioned is possible, in a main node, but not https://github.com/availproject/avail-substrate-api-sidecar code

**Comment by malingzhao** [comment]
ok
