### ISSUE TITLE
avail-substrate-api-sidecar

### ISSUE THREAD

**Issue by yaoyf888** [availproject/avail#621]
{
    "code": 500,
    "message": "createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.killPrefix:: Struct: failed on args: {\"prefix\":\"Bytes\",\"subkeys\":\"u32\"}:: decodeU8aStruct: failed at 0x0300b645fbddf5d8407f771af3e2c082… on prefix (index 1/2): Bytes:: Bytes length 4215649792 exceeds 10485760",
    "stack": "Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.killPrefix:: Struct: failed on args: {\"prefix\":\"Bytes\",\"subkeys\":\"u32\"}:: decodeU8aStruct: failed at 0x0300b645fbddf5d8407f771af3e2c082… on prefix (index 1/2): Bytes:: Bytes length 4215649792 exceeds 10485760\n    at createTypeUnsafe (/Users/yaoyf/WorkSpace/Bitmart/code/avail-substrate-api-sidecar/node_modules/@polkadot/types-create/cjs/create/type.js:54:22)\n    at TypeRegistry.createTypeUnsafe (/Users/yaoyf/WorkSpace/Bitmart/code/avail-substrate-api-sidecar/node_modules/@polkadot/types/cjs/create/registry.js:230:52)\n    at RpcCore._formatOutput (/Users/yaoyf/WorkSpace/Bitmart/code/avail-substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:331:25)\n    at RpcCore._formatResult (/Users/yaoyf/WorkSpace/Bitmart/code/avail-substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:169:20)\n    at callWithRegistry (/Users/yaoyf/WorkSpace/Bitmart/code/avail-substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:190:25)",
    "level": "error"
}

**Comment by yaoyf888** [comment]
i use this code：https://github.com/availproject/avail-substrate-api-sidecar

**Comment by yaoyf888** [comment]
@QEDK Can you help me?

**Comment by kroos47** [comment]
@yaoyf888 Are you running the sidecar locally?(like building from source and not docker), If yes did you add the avail specific types which is in the root of the repo and the url to the env? If you did all these above steps then what was the request that you were trying?

**Comment by yaoyf888** [comment]
I do want to run sidecar using the source code, but get an error when requesting block details. How do I add the avail type and env url in the repo root directory? I am currently using docker pull availj/sidecar-api:zenitsu, this docker is OK

**Comment by kroos47** [comment]
so try to add the files to the .env file or so `export SAS_SUBSTRATE_URL=wss://mainnet-rpc.avail.so/ws` and export `SAS_SUBSTRATE_TYPES_BUNDLE="<_path_to_types.json_files_in_local_repo_"`

**Comment by yaoyf888** [comment]
docker pull availj/sidecar-api:zenitsu Is this available on the mainnet? Will that be a problem?

**Comment by kroos47** [comment]
yes it is available on the mainnet! But make sure you pass URL and Types when running

**Comment by kroos47** [comment]
@yaoyf888 let me know if its resolved the issue

**Comment by kroos47** [comment]
closing this for now!
