### ISSUE TITLE
feat: Can you recover tokens claimed with ethereum account ?

### ISSUE THREAD

**Issue by MrishoLukamba** [availproject/avail#623]
Asking for help as my eligibility was based on my Github so you can verify but I would like some help as I did claim with wrong account type and the balance is not reflected. @praetoriansentry @QEDK @markopoloparadox @Aphoh @estensen

**Comment by prabal-banerjee** [comment]
Hi. This is not the right forum to discuss the particular problem as it has nothing to do with the avail node codebase. Kindly use official Discord or TG channels to raise the problem. Plus, provide more details on "wrong account type" and "balance not reflected". Thanks.
